coverage:

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        threshold: 0.5         # allowed to drop X% and still result in a "success" commit status

    patch:                     # pull requests only: this commit status will measure the
                               # entire pull requests Coverage Diff. Checking if the lines
                               # adjusted are covered at least X%.
      default:
        enabled: yes           # must be yes|true to enable this status
        threshold: 0.5         # allowed to drop X% and still result in a "success" commit status

